---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: src/data/notifications.json
  label: Notifications
- type: document
  path: src/data/cmsConfig.json
  label: Config
- type: directory
  path: src/pages
  label: Pages
  create: all
  match: "**/*-cms.md"
  exclude: src/pages/**/*(photos|donors).md
  templates:
  - article
  - home
- type: document
  path: src/data/lang.json
  label: Dictionary
upload_dir: src/static/uploads
public_path: "/images/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
