---
label: cmsConfig
hide_body: true
fields:
- name: latestDate
  type: datetime
  label: Friss dátum
  description: A Friss oldalon ettől a dátumtól kezdődik a képek listázása.
  config:
    required: true
    date_format: ''
    time_format: 
    display_utc: true
    export_format: ''
- name: tax1percent
  type: select
  default: '0'
  config:
    required: false
    options:
    - '1'
    - '0'
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Adó 1% banner megjelenítése
pages:
- src/data/cmsConfig.json
