export default {
  PHOTO_SOURCE: "http://fortepan.hu/_photo/display/",
  PHOTO_SOURCE_LARGE: "/download/",
  THUMBNAILS_QUERY_LIMIT: 30,
  BREAKPOINT_PHONE_XS: 330,
  BREAKPOINT_PHONE_SM: 390,
  BREAKPOINT_PHONE: 640,
  BREAKPOINT_TABLET: 768,
  BREAKPOINT_DESKTOP: 1024,
  BREAKPOINT_DESKTOP_LG: 1220,
}
